/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpCaretBottom: typeof import('~icons/ep/caret-bottom')['default']
    IEpCaretDown: typeof import('~icons/ep/caret-down')['default']
    IEpCaretRight: typeof import('~icons/ep/caret-right')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    Image: typeof import('./src/components/image/image.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTag: typeof import('./src/components/select-tag/select-tag.vue')['default']
    Tag: typeof import('./src/components/select-tag/tag.vue')['default']
  }
}
